[#13] Menu API 추가
f-lab-edu/delivery-food pull request #13
Opened 2022-10-03 04:38 UTC by cyh789

- MenuService 관련 API 추가

2022-10-03 04:39 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>      }
현경님이 작성하신 부분인데 제가 API 명세를 잘못보고 작성했던 중복된 부분입니다. conflict 방지를 위해 해당 로직은 제거했습니다.

2022-10-03 04:39 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>      }
현경님이 작성하신 부분인데 제가 API 명세를 잘못보고 작성했던 중복된 부분입니다. conflict 방지를 위해 해당 로직은 제거했습니다.

2022-10-03 04:41 UTC, cyh789 commented on src/main/java/com/deliveryfood/dao/RestaurantDao.java
>      }
오탈자 수정 (패키지 주소가 부정확해도 쿼리가 수행되긴 하네요)

2022-10-03 22:10 UTC, f-lab-steve requested changes

2022-10-03 22:10 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +import java.util.*;
이건 구글 코드 스타일 가이드에서도 나오는 내용인데, wildcard import를 지양해야합니다. 이유는 사용하려는 클래스가 어디에서 import된 클래스인지 알아야합니다. *로 생략해버리면 특히 코드리뷰 단계에서 해당 정보가 모두 사라지는 것이기 때문에 IDE의 힘 없이 리뷰하기가 점점 어려운 구조가 됩니다.

IDE에 보통 code style관련하여 설정하는 곳이 있고, "import 가 몇개 이상이면 wildcard 사용" 같은 내용으로 있으니 해당 설정을 엄청 큰 값으로 변경하거나 해제하시면 좋겠습니다. 더 좋은 방법은 google style guide에 올라와 있는 설정값으로 IDE셋팅을 덮어씌우는 겁니다.

2022-10-03 22:10 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +    public MenuDto findMenus(@PathVariable String restaurantId
여기도 저번에 얘기 드렸던 DTO가 어디까지 노출 되느냐에 대한 문제가 있습니다.

2022-10-03 22:10 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/MenuServiceImpl.java
> +        MenuDto menuDto = MenuDto.builder()
find에서 MenuDTO를 이용하여 parameter를 넘기는 것은 바람직해보이지 않습니다. MenuDTO는 저희가 DB에 저장된 entity를 표현하는 class로 정의를 했습니다. 그런 class를 parameter를 추상화하는데 다시 이용하게 되면, class의 역할이 점점 복잡해지고, 특정 사용케이스 마다 사용하는 방법이 달라져서 추가적으로 더 복잡해집니다. 개인적으로는 find같은 operation들은 pk(보통 1~2 컬럼?)로 서칭하는게 대부분이기에 래핑이 필요 없어 보입니다만, mybatis를 이용하는데 있어서 object를 넘기는게 편해서 추상화할 class가 필요하다면 다른 이름으로 만들어서 사용하는 것을 추천드립니다.

2022-10-04 11:13 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +import java.util.*;
미처 생각해보지 못한 부분이네요. 참고하겠습니다.

2022-10-04 11:14 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +    public MenuDto findMenus(@PathVariable String restaurantId
네 VO를 구분해서 사용하는 부분(Request, Input, Dto)은 현경님과 협의 후 네이밍규칙을 정해서, 리팩터링 PR을 통해 진행하겠습니다.

2022-10-04 11:18 UTC, cyh789 commented on src/main/java/com/deliveryfood/service/MenuServiceImpl.java
> +        MenuDto menuDto = MenuDto.builder()
네 Controller -> Service 부분을, Input에서 Reqeust로 변경하고
Service -> DAO를 DTO에서 Input로 변경하는 방향으로 진행하겠습니다.

2022-10-04 11:18 UTC, merged