[#21] Spring Security 인증 구현
f-lab-edu/delivery-food pull request #22
Opened 2022-10-10 11:22 UTC by haenlee

1. UsernamePasswordAuthenticationFilter, AuthenticationProvider 재정의
2. Role 추가 (USER, RESTAURANT, RIDER, NOT_AUTH)
3. 기존 MemberSession 대신 @AuthenticationPrincipal로 변경

2022-10-11 16:52 UTC, f-lab-steve requested changes

2022-10-11 16:52 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/model/CustomUserDetails.java
> +    private String authority;
Authority가 n개여야 하나의 계정이 user, rider, restaurant 등의 권한을 가질 수 있게 될 것 같습니다.

2022-10-11 16:52 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/MemberService.java
> +        memberDto.setRole(role);
하나의 member는 하나의 role을 갖는다가 여기서부터 시작된 것이군요. 이 부분은 개선되어야 할 것 같습니다.

2022-10-14 04:49 UTC, haenlee commented on src/main/java/com/deliveryfood/service/MemberService.java
> +        memberDto.setRole(role);
3e4abe54a7634827afe44ee7a7aef19ec3c6b340 에서 수정하였습니다~

2022-10-14 16:45 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/config/CustomAuthenticationProvider.java
> +        CustomUserDetails user = (CustomUserDetails) memberService.loadUserByUsername(username);
여기서 user가 null인 경우도 있습니다.

2022-10-15 03:22 UTC, haenlee commented on src/main/java/com/deliveryfood/config/CustomAuthenticationProvider.java
> +        CustomUserDetails user = (CustomUserDetails) memberService.loadUserByUsername(username);
memberService.loadUserByUsername에서 null이 되는 경우는 DB에서 member를 못찾는 경우여서, loadUserByUsername에서 Exception 처리 하였습니다.
045d5793976965c049970bcc0d7967de700a671d 에서 수정되었습니다~

2022-10-18 17:13 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/config/CustomAuthenticationProvider.java
> +        CustomUserDetails user = (CustomUserDetails) memberService.loadUserByUsername(username);
앗 그렇군요. [interface](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/UserDetailsService.html#loadUserByUsername(java.lang.String))정의에 맞춰서 NullPointerException (NPE) 보다는 UsernameNotFoundException이 좋아보입니다.

2022-10-19 01:46 UTC, haenlee commented on src/main/java/com/deliveryfood/config/CustomAuthenticationProvider.java
> +        CustomUserDetails user = (CustomUserDetails) memberService.loadUserByUsername(username);
6d17abca860a39ffcd526c80c2b9cd87982744bd 에서 수정하였습니다~

2022-10-21 09:14 UTC, merged