[#23] 서비스 VO 클래스 생성
f-lab-edu/delivery-food pull request #24
Opened 2022-10-10 13:50 UTC by haenlee

1. controller에서 사용하는 클래스 이름을 request라고 정의하였습니다.
2. service에서 사용하는 클래스 이름을 vo라고 정의하였습니다.
3. 위 규칙에 따라 controller, service 정리하였습니다.

2022-10-11 17:02 UTC, f-lab-steve requested changes

2022-10-11 17:02 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +        return null;
테스트케이스에서 response를 full로 검증하지 않아서 문제가 없었을 수도 있는데, `@RestController`를 사용하거나 `@ResponseBody`를 이용해야 object serialization을 수행해줍니다.

2022-10-11 17:02 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/UserController.java
> +import com.deliveryfood.vo.UserRegisterVO;
이제 패키지 구조를 보면. model이라는 것 아래에도 interface의 input output을 정의하는 model들이 들어가고, vo 패키지 안래에는 service를 위한 input output model들이 정의되기 시작했습니다. 둘다 model인데 애매한 분류가 생긴거죠. 

이런 경우 최상위에 model패키지 vo패키지 형태로 가는것 보다는 controller.model, service.model 등으로 하위 패키지에 넣는게 더 의미가 맞게 응집되어있다고 생각합니다. 

더 좋은 방법이 있다면 해당 방향으로 패키지 분류를 바꿔보는 것도 좋습니다.

2022-10-17 16:26 UTC, haenlee commented on src/main/java/com/deliveryfood/controller/UserController.java
> +import com.deliveryfood.vo.UserRegisterVO;
main 브랜치로 머지가 어느정도 완료되면 controller.model, service.model로 변경하도록 하겠습니다.

2022-10-17 16:28 UTC, haenlee commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +        return null;
d57e1a566fa1f7f00d2be12eb68641eb6756c402 에서 변경되었습니다~
Restaurant 관련해서는 윤혁님 정리가 필요할 것 같습니다.

2022-10-18 20:24 UTC, f-lab-steve approved these changes

2022-10-21 09:18 UTC, merged