[#26] Option, SubOption API 추가
f-lab-edu/delivery-food pull request #27
Opened 2022-10-13 04:59 UTC by cyh789

- Option API 추가
- SubOption API 추가
- 정책상 CUD 기능은 제공하지 않기에 조회 API만 추가

2022-10-13 16:31 UTC, f-lab-steve requested changes

2022-10-13 16:31 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +import com.deliveryfood.model.*;
wildcard import 는 안쓰시는게 좋습니다.

2022-10-13 16:31 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +    private final ISubOptionService subOptionService;
Option이 따로 서비스로 빠져야하냐? 에 대해서 의견이 많으시겠지만, Menu에 종속적인 부분이라 MenuService안에 있는 것도 좋아보입니다.

2022-10-13 16:31 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +    public OptionInput findOptionById(@RequestBody OptionInput optionInput) {
이 API는 설계가 잘못된 것 같습니다. 

menu에 해당하는 option을 불러오는 API가 존재한다는 이야기는 'menu를 조회하는 API에서 menu를 반환할 시에 option을 제공하지 않는다'는 말과 같은데 option id를 모르는 클라이언트가 option id를 통해 option을 조회하는건 불가능하겠습니다. 

아마 menuId만 받아서 해당 메뉴에 있는 option들을 찾으려고 했던게 아닐까 싶습니다?

보다 근본적인 API 설계 문제는 레스토랑 하나에 있는 메뉴들을 조회하는데 있어서 O(menu * options) 의 요청이 필요하다는 점입니다.

2022-10-14 01:24 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +    public OptionInput findOptionById(@RequestBody OptionInput optionInput) {
코멘트 주신 부분 반영하여 변경작업 PR 준비하도록 하겠습니다

2022-10-18 02:29 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +import com.deliveryfood.model.*;
이전에 pr주신 내용에서도 동일한 의견을 주신적이 있어서, 그때 wildcard import를 제외했었는데 자동으로 사용이 되었네요. 확인해보니 intellij 셋팅 중 wildcard import 에 대한 설정이 가능하여 count를 늘려서 해결하였습니다.

2022-10-18 08:35 UTC, cyh789 commented
변경에 대한 PR 진행 예정

2022-10-18 08:35 UTC, closed without merging