[#30] RestaurantUser API 추가
f-lab-edu/delivery-food pull request #31
Opened 2022-10-17 16:24 UTC by haenlee

1. 가게 회원에 대한 기본적인 API를 추가하였습니다.
2. 기존 Restaurant로 시작하는 클래스는 가게 관련 기능 전용으로 사용해야 할 것 같습니다.
3. 따라서 가게 회원의 클래스의 이름은 RestaurantUser로 시작하도록 하였습니다.

2022-10-18 17:03 UTC, f-lab-steve requested changes

2022-10-18 17:03 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/dto/RestaurantUserDto.java
> +    private LocalDateTime udtDt;
udt도 NonNull이 될 수 있을 것 같습니다.

최초 udtDt는 regDt와 같은 값을 가질 수 있겠죠.

2022-10-18 17:03 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/RestaurantUserService.java
> +public class RestaurantUserService extends MemberService implements IRestaurantUserService {
이제 MemberService가 여러개가 등장하면서 생기는 문제는 SpringSecurity쪽 설정에서 MemberService를 inject할 때 어떤 MemberService를 inject할지 결정을 못한다는 점입니다. SpringSecurity쪽이 수정되거나, UserService가 MemberService를 상속(inheritance)받아서 처리하는 방식이 아닌 composite개념으로 변경해야 할 것 같습니다. (UserService가 MemberService를 injection받고, 해당 object를 사용하는 개념)

2022-10-21 15:50 UTC, haenlee commented on src/main/java/com/deliveryfood/dto/RestaurantUserDto.java
> +    private LocalDateTime udtDt;
ebf10eb1734947cd1d77fef8eb1c250fde14184b 에서 수정하였습니다~

2022-10-21 15:53 UTC, haenlee commented on src/main/java/com/deliveryfood/service/RestaurantUserService.java
> +public class RestaurantUserService extends MemberService implements IRestaurantUserService {
현재 다른 branch를 바라보고 있다가 main을 바라보게 했더니 많은 부분이 conflict되고 커밋 로그가 중복되는 현상이 생겼습니다.
#30 에서 MemberService관련하여 변경된 부분이 있어 #30 머지 후 해당 기능 구현하겠습니다.

2022-10-28 11:14 UTC, merged