[#26_2] Option, SubOption API 추가
f-lab-edu/delivery-food pull request #32
Opened 2022-10-18 08:37 UTC by cyh789

- Option API 추가
- SubOption API 추가
- wildcard import 제거
- 옵션 조회 제거 및 하위옵션 조회 개선

2022-10-18 08:38 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> -
해딩 기능과 옵션 조회 기능에서 착오가 있었던 것으로 확인되어 해당 기능 제거하였습니다.

2022-10-18 08:41 UTC, cyh789 commented
해당PR은 이전 #26과 비교하여 RestaurantController와 RestaurantControllerTest 외 특별한 변경점 없으니 참고바랍니다.

2022-10-20 22:14 UTC, f-lab-steve requested changes

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>      public void createMenuById(@PathVariable String restaurantId
API가 추가되면서 method name에 있는 Id가 무엇을 지칭하는지 알 수 없게 되었습니다. 

여기의 Id는 restauratntId이고
아래쪽에 있는 
 `modifyMenuById`에서 의 Id는 사실 restaurantId와 menuId를 둘 다 받아야하는 것이고
`findSubOptionById`는 Id가 menuId인 것이죠. 

내부 구현을 봐야만 확실하게 알 수 있으니 명확하게 개선할 필요가 있습니다.

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +            return subOptionOutputs;
생각의 흐름대로 따라와보자면 이 컬렉션안에 suboptions들을 모두 모아서 리턴하려고 했던 것 같습니다만, 실제로는 하나의 옵션에 대해서만 조회한 후에 리턴하게 됩니다.

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +            return subOptionOutputs;
또 option에 대한 서브옵션이 무조건적으로 존재하는지는 모르겠습니다만, 옵션중 서브 옵션이 없는 경우에는 중간에 exception을 던지기 때문에 조회가 실패할 수 있을 것 같습니다.

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +        List<SubOptionInput> subOptionOutputs = null;
아래의 로직이 완벽하게 수행된다는 전제하에 null이 리턴될 가능성이 없습니다만, 최대한 null사용을 배제해야한다고 생각합니다. null이 돌아다니기 시작하면 방심하는 순간 NPE가 나거든요. Collections.emptyList()를 사용해서 빈 것을 기본값으로 내려주거나, 아래의 로직이 고쳐진다면 new ArrayList<>()같은 형태로 초기화가 되어야겠죠.

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/dao/OptionDao.java
> +        log.info("findOptionById DAO 호출");
이런 로그는 debug나 trace가 알맞다고 생각됩니다.

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/MenuService.java
> +//    MenuDto findMenus(MenuInput menuInput);
주석으로 남기는 이유가 있을까요?

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/OptionService.java
> +        log.info("findOptionById 서비스 호출");
이런것도 debug나 trace에 가깝습니다.

2022-10-20 22:14 UTC, f-lab-steve commented on src/main/resources/sql/create_options.sql
> +insert into options(option_id, menu_id, name)
테스트용 데이터가 DB에 필요하다면 Test class에서 @Before @After 같은 기능을 이용하여 잠시 넣었다가 빼는 게 좋을 것 같습니다.  Transaction이 설정되어야 테스트 실행후에 롤백을 할 수 있을테니 트랜잭션 설정이 우선되어야 할 것 같습니다. 

(저만 그렇게 생각하는지 모르겠습니다만) 이 파일은 DDL관리용으로 이해하고 있습니다.

2022-10-21 01:24 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +            return subOptionOutputs;
아 이부분(for문 안에있는 return subOptionOutputs)은 오타입니다. 나름대로 검수를 하였다고 생각했는데 실수가 있었습니다.

2022-10-21 01:28 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +            return subOptionOutputs;
서브옵션이 조회되지 않을 수 있다는 가정하에, 해당 케이스에는 일부러 exception을 던지도록 구현한 것이 맞습니다.
다만 스티브님 코멘트를 보고 한번 더 생각해보니, 조회되는 서브옵션이 없을 경우 오류응답(화면상 옵션 구성 실패) 하는것보다 빈값을 응답하는게 더 바라직한 것 같아 방향을 수정해보겠습니다.

2022-10-21 01:31 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +        List<SubOptionInput> subOptionOutputs = null;
감사합니다. 좋은 내용을 배웠습니다. Collections.EMPTY_LIST 로 변경하여 NPE를 최대한 배제해 보겠습니다.

2022-10-21 01:34 UTC, cyh789 commented on src/main/java/com/deliveryfood/service/MenuService.java
> +//    MenuDto findMenus(MenuInput menuInput);
제가 로직구현PR을 먼저 작성하고, 이후에 리팩토링 PR을 따로 작성하려고 하다보니 이런부분(오탈자, TODO처리, 주석처리)이 자주 발생하는 것 같습니다. PR에서 의도를 파악하기 힘들게 할 수 있을것을 고려하지 못하였기에 다음부터는 한번에 처리해서 작성할 수 있도록 의식적으로 진행해보겠습니다.

2022-10-21 01:39 UTC, cyh789 commented on src/main/resources/sql/create_options.sql
> +insert into options(option_id, menu_id, name)
감사합니다. 좋은 내용을 배웠습니다. 덕분에 테스트용 데이터는 @before를 이용하도록 하고, 해당 파일은 DDL 관리용으로 완전히 전환시킬 수 있을 것 같습니다.

2022-10-21 01:40 UTC, closed without merging

2022-10-21 01:41 UTC, cyh789 commented
PR내용 반영하여 개선 예정

2022-10-22 04:52 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +        List<SubOptionInput> subOptionOutputs = null;
EMPTY_LIST와 emptyList()의 차이점을 공부해보시면 좋을 것 같은데요, EMPTY_LIST는 rawtype을 사용하기 때문에 낮은 자바 버전을 (1.5 미만, 구시대의 유물) 쓰는게 아니라면 무조건 emptyList(), emptySet(), emptyMap(),... 을 사용해야합니다.