[#26_4] Option, SubOption API 추가
f-lab-edu/delivery-food pull request #37
Opened 2022-10-25 06:55 UTC by cyh789

1. build.gradle
  - style 개선
2. RestaurantController.java
  - addAll() 메소드 사용하도록 개선
  
* ArrayList에서 addAll() 메소드 사용시 Collection 객체를 파라미터로 입력받아서 List의 뒤에 이어붙여 주는 것을 확인하였습니다. ArrayList.addAll() 메서드를 사용하는 것으로 개선하였습니다.

여담으로, stackoverflow 에서 용례를 검색해보다가 ArrayList.addAll 보다 Collections.addAll의 성능이 더 좋을 수 있다는 글을 확인하였습니다.
 (1) ArrayList의 addAll()은 실행 도중 Arrays.asList가 실행되며 array 뒤에 붙을 List<E>가 생성되는 단계가 있음. Collections의 addAll() 메서드 사용시 이 단계를 생략하고, Iterable<E>를 array의 반복으로 대체 (중개자 List가 생성되지 않음)
   - 참고 : https://stackoverflow.com/questions/3343766/why-is-collections-addall-supposed-to-be-faster-than-c-addall
 (2) Collections.addAll은 컬렉션에 몇 가지 요소만 반복적으로 추가할 때 더 빠를 수 있지만 이 경우가 성능 병목 현상이 되지는 않음
 (3) 이펙티브 자바(아이템 28. 배열보다는 리스트를 사용하라) 에서도 배열보다는 제네릭 타입의 사용을 권장 (컴파일타임 타입체크로 안전성 보장의 차이)
 (4) 결론, ArrayList.addAll()을 사용

3. OptionMapper.xml / SubOptionMapper.xml
  - WHERE 조건절 추가하도록 개선 (DELETE by KEYID)
  
4. RestaurantControllerTest.java
  - 테스트 더미데이터 생성 관련하여, @BeforeEach / @AfterEach 어노테이션이 사용된 메서드의 실행순서 보장할 수 있는 구조로 개선

2022-10-25 06:56 UTC, cyh789 commented on build.gradle
>  	testImplementation 'org.springframework.boot:spring-boot-starter-test'
style 개선

2022-10-25 06:56 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>  import java.util.List;
wildcard import 제거

2022-10-25 06:56 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>      @GetMapping("/{restaurantId}/menus")
신규추가된 "findSubOptions" 메서드와 개념적으로 혼동하여 생성했던 "findMenus" 관련 삭제

2022-10-25 06:56 UTC, cyh789 commented on src/main/java/com/deliveryfood/dao/MenuDao.java
>      public List<MenuDto> findMenuById(MenuDto menuDto) {
마찬가지로, "findMenus" 관련 삭제

2022-10-25 06:58 UTC, cyh789 commented on src/main/java/com/deliveryfood/dao/OptionDao.java
> +
DELETE 쿼리에 WHERE 조건절 추가하도록 개선 (DELETE by KEYID)

2022-10-25 06:58 UTC, cyh789 commented on src/main/java/com/deliveryfood/dao/SubOptionDao.java
> +
DELETE 쿼리에 WHERE 조건절 추가하도록 개선 (DELETE by KEYID)

2022-10-25 06:59 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
> +
addAll() 메소드 사용하도록 개선

* ArrayList에서 addAll() 메소드 사용시 Collection 객체를 파라미터로 입력받아서 List의 뒤에 이어붙여 주는 것을 확인하였습니다. ArrayList.addAll() 메서드를 사용하는 것으로 개선하였습니다.

여담으로, stackoverflow 에서 용례를 검색해보다가 ArrayList.addAll 보다 Collections.addAll의 성능이 더 좋을 수 있다는 글을 확인하였습니다.
 (1) ArrayList의 addAll()은 실행 도중 Arrays.asList가 실행되며 array 뒤에 붙을 List<E>가 생성되는 단계가 있음. Collections의 addAll() 메서드 사용시 이 단계를 생략하고, Iterable<E>를 array의 반복으로 대체 (중개자 List가 생성되지 않음)
   - 참고 : https://stackoverflow.com/questions/3343766/why-is-collections-addall-supposed-to-be-faster-than-c-addall
 (2) Collections.addAll은 컬렉션에 몇 가지 요소만 반복적으로 추가할 때 더 빠를 수 있지만 이 경우가 성능 병목 현상이 되지는 않음
 (3) 이펙티브 자바(아이템 28. 배열보다는 리스트를 사용하라) 에서도 배열보다는 제네릭 타입의 사용을 권장 (컴파일타임 타입체크로 안전성 보장의 차이)
 (4) 결론, ArrayList.addAll()을 사용

2022-10-25 07:02 UTC, cyh789 commented on src/main/resources/sql/create_sub_options.sql
> -;
DDL 형상관리만 할 수 있도록 개선

2022-10-25 07:02 UTC, cyh789 commented on src/test/java/com/deliveryfood/controller/RestaurantControllerTest.java
테스트 더미데이터 생성 관련하여, @BeforeEach / @AfterEach 어노테이션이 사용된 메서드의 실행순서 보장할 수 있는 구조로 개선

2022-10-28 03:58 UTC, f-lab-steve requested changes

2022-10-28 03:58 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>      @GetMapping("/{restaurantId}/menus")
이전에 올라왔던 내용같은데, 제 착각일까요?

2022-10-28 03:58 UTC, f-lab-steve commented on src/test/java/com/deliveryfood/controller/RestaurantControllerTest.java
> +        createOptionDummyData();
아무리 테스트 코드라도 이런 방법으로 상태가 변경되는 것은 지양하는게 좋습니다.

상수같은 데이터가 일관성 없게 정의 혹은 변경되고 method의 동작을 좌지우지하는 형태입니다. 

parameter를 통해 메소드에 전달하는 방식으로 하거나, 전달하기가 싫다면 적어도 상수 형태로라도 정의되면 좋겠습니다.

2022-10-28 04:45 UTC, cyh789 commented on src/main/java/com/deliveryfood/controller/RestaurantController.java
>      @GetMapping("/{restaurantId}/menus")
PR이 길어져서, 이전에 올라왔던 내용이 포함되어 있는게 맞습니다!

2022-10-28 04:46 UTC, cyh789 commented on src/test/java/com/deliveryfood/controller/RestaurantControllerTest.java
> +        createOptionDummyData();
테스트코드라고 생각하여 너무 규칙성없이 작성했던 것 같네요. 앞으로는 parameter를 통해 메소드에 전달하는 방식으로 개선하겠습니다.

2022-10-28 04:51 UTC, cyh789 commented on src/test/java/com/deliveryfood/controller/RestaurantControllerTest.java
> +        createOptionDummyData();
머지 후에, 해당 부분만 수정하여 PR 새로 올리도록 하겠습니다.

2022-10-28 04:53 UTC, merged