[#34] CI 테스트 적용
f-lab-edu/delivery-food pull request #42
Opened 2022-11-06 17:22 UTC by haenlee

- Jasypt 라이브러리를 사용해서 DB 개인 정보 암호화를 적용했습니다.
- User, Restaurant, Rider, Cart 관련해서 테스트 성공할 수 있도록 기능을 수정하였습니다.
- 현재 윤혁님이 작성한 테스트로 인해 테스트 결과 실패로 노출되고 있습니다.

2022-11-07 19:16 UTC, f-lab-steve requested changes

2022-11-07 19:16 UTC, f-lab-steve commented on src/test/java/com/deliveryfood/controller/CartControllerTest.java
> +        memberDao.deleteAllMember();
아무리 테스트 용도라지만 deleteAll을 허용해주는 것은 굉장히 위험하다고 생각합니다. 필요하다면 특정 id를 골라서 지울 수 있도록 변경하는게 좋을 것 같습니다.

제일 좋은 것은 테스트 케이스에 Transaction을 걸고 자동으로 rollback이 되도록 하는거겠지만요

2022-11-07 19:16 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/config/JasyptConfig.java
> +    @Bean("jasyptStringEncryptor")
이 Bean이 어떤식으로 연계되는 것인지 PR에 설명이 있다면 좋을 것 같습니다.

2022-11-07 19:16 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/config/JasyptConfig.java
> +    @Bean("jasyptStringEncryptor")
이 기능이 제대로 적용된 것을 어떻게 테스트할 수 있었을까요?

2022-11-08 08:55 UTC, haenlee commented on src/test/java/com/deliveryfood/controller/CartControllerTest.java
> +        memberDao.deleteAllMember();
특정Id로 제거될 수 있도록 [7160c71](https://github.com/f-lab-edu/delivery-food/pull/42/commits/7160c71da68a5de08d88127c1d67a0c6d85e31b2) 에서 수정하였습니다.
윤혁님이 Transaction 기능 올려주시면 Transation rollback으로 변경하겠습니다~

2022-11-08 08:56 UTC, haenlee commented on src/main/java/com/deliveryfood/config/JasyptConfig.java
> +    @Bean("jasyptStringEncryptor")
[13fcf4a](https://github.com/f-lab-edu/delivery-food/pull/42/commits/13fcf4adff65ca947ac69f22a104a70323eed875)에서 테스트 코드 추가하여 테스트하였습니다.

2022-11-11 09:09 UTC, merged