[#32_2] 트랜잭션 매니저, DB분리 추가
f-lab-edu/delivery-food pull request #44
Opened 2022-11-09 01:24 UTC by cyh789

- 트랜잭션 매니저 추가
- DB분리 추가
- 관련 테스트 개선

2022-11-12 04:53 UTC, f-lab-steve requested changes

2022-11-12 04:53 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/test/MenuServiceToTransactionTest.java
> +public class MenuServiceToTransactionTest {
이런 메소드 없이 테스트를 작성하는게 어려웠을 수 있는데요, 그렇지만 이런 테스트용 코드를 테스트 코드가 아닌 곳에 작성해서 사용하는 것은 바람직하지 않은 것 같습니다.

2022-11-12 04:53 UTC, f-lab-steve commented on src/test/java/com/deliveryfood/databases/DataSourceTest.java
> +        String url = environment.getProperty("spring.datasource.master.jdbc-url");
FYI: 사실 이 부분이 굉장히 논쟁이 많은 부분 중 하나인데요. 

해당 테스트의 목적은 master에 해당하는 property가 제대로 inject가 되었는가에 대한 것이라. 윤혁님이 작성하신대로 기대하는 property를 직접 가져와서 inject되어야 하는 대상에 실제로 같은 값이 들어갔는지 확인하는 것이기 때문에 원하는 동작을 수행하고 있다고 할 수 있습니다.

근데 또 어떤 사람들은 테스트 코드는 기대하는 결과값이 명시적으로 눈에 보여야한다고 말하는 사람도 있습니다. master.jdbc-url에 A라는 값이 있었다면 테스트 코드에서는 A라는 값을 명시적으로 expected value로 지정하는 것이죠. 

저는 어떤 것이 옳은 방향이라고 딱 집어 말할 순 없고, 테스트를 작성할때는 개인적으로 2가지 방식이 적절하게 섞어야 한다고 봅니다.

2022-11-12 04:53 UTC, f-lab-steve commented on src/test/java/com/deliveryfood/databases/ReplicationTest.java
> +    void readOnlyTransactionTest2() throws Exception {
이런건 비즈니스 코드를 이용하여 테스트를 하기에 적합하지 않은 내용 같습니다. 그리고 테스트 하고자 하는 내용이 사실 무엇인지 잘 이해가 가지 않습니다. 어떤 의도였을까요?

제가 생각하기엔 하고자 하는 일은 read only로 트랜잭션이 선언되었을 때 replica를 가르키고 있는 datasource를 이용하는지에 대한 검증인 것 같습니다. 위에서 determineCurrentLookupKey를 호출하여 String value가 제대로 나온 것을 검증하는 것을 했었으니 지금은 제대로 된 datasource가 나오는지를 보고 싶었던게 아닐까 싶습니다.

2022-11-12 04:53 UTC, f-lab-steve commented on src/test/java/com/deliveryfood/databases/TransactionTest.java
> +    void txRollbackTest() {
이런 부분은 선언적 트랜잭션이라는 것에 얽매이다보니 사고의 틀이 갇혀버려 이렇게 테스트를 작성하게 되지 않았나 싶습니다. 

트랜잭션을 이용하기 위해서는 코드를 통해 제어하는 방법 또한 있습니다. 트랜잭션이 실행중인 내부에서 변경을 하고 rollback을 했을 때 database에 변경이 기록되지 않음을 테스트 하면 간결할 것 같습니다.

2022-11-12 04:53 UTC, f-lab-steve commented on src/test/java/com/deliveryfood/databases/TransactionTest.java
> +    void txRollbackTest2() {
모든 uncaught exception에 대해서 롤백이 되는게 맞을 것 같습니다. 해당 내용을 테스트 하는 것이였다면 checked와 unchecked에 차이를 두면 안될 것 같습니다.

2022-11-14 15:22 UTC, cyh789 commented
피드백 받은 내용 적용하여 새로운 PR 작성

2022-11-14 15:22 UTC, closed without merging