[#8] 회원 API 추가 구현
f-lab-edu/delivery-food pull request #9
Opened 2022-09-30 13:37 UTC by haenlee

1. 회원 조회 API
2. 회원 정보 수정 API

2022-09-30 18:51 UTC, f-lab-steve requested changes

2022-09-30 18:51 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/controller/UserController.java
> +    public void findUser(@PathVariable String email) {
여기서 email로 변경되었는데, path 상에선 아직 userId입니다. 아마 테스트코드가 없어서 해당 케이스를 감지하지 못했을 수 있는데, assign이 안될 겁니다.

2022-09-30 20:32 UTC, f-lab-steve requested changes

2022-09-30 20:32 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/UserServiceImpl.java
> +        if(!userDto.getPassword().equals(userRequest.getPassword())) {
password는 위에서 BCrypt를 적용했기 때문에 평문 비교가 불가능합니다. BCrypt에 있는 check method를 사용하여 비교하여야합니다.

2022-10-01 04:25 UTC, haenlee commented on src/main/java/com/deliveryfood/service/UserServiceImpl.java
> +        if(!userDto.getPassword().equals(userRequest.getPassword())) {
해당 사항 #10 PR에서 수정되었습니다~

2022-10-01 04:35 UTC, f-lab-steve commented on src/main/java/com/deliveryfood/service/UserServiceImpl.java
> +        if(!userDto.getPassword().equals(userRequest.getPassword())) {
#10 에서도 login은 반영이 안되어있습니다. 수정이 필요합니다.

2022-10-01 12:14 UTC, merged